---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/part-of: knot
  name: knot-controller-manager
  namespace: knot
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knot-sa-role
  namespace: knot
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: knot
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knot-controller-manager-binding
  namespace: knot
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: knot
subjects:
  - kind: ServiceAccount
    name: knot-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knot-sa-role
