package doc

import (
	"github.com/spf13/cobra"
)

// Test to see if we have a reason to print 'Available commands' information in docs
// This is a test for a subcommand which is both not deprecated and not the autogenerated help command
func hasAvailableCommands(cmd *cobra.Command) bool {
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		return true
	}
	return false
}

type byName []*cobra.Command

func (s byName) Len() int           { return len(s) }
func (s byName) Swap(i, j int)      { s[i], s[j] = s[j], s[i] }
func (s byName) Less(i, j int) bool { return s[i].Name() < s[j].Name() }
